### ISSUE TITLE
"Stand-alone Server Example" error camera.unpipe is not a function

### ISSUE THREAD

**Issue by cryol** [mmaelzer/mjpeg-camera#5]
[root@cctv]# cs -l http://10.0.0.200:8008 -n "cam"
=== cam camera server listening on 8080 ===

after close browser:

```
/usr/lib/node_modules/mjpeg-camera/cs:50
      camera.unpipe(ws);
             ^

TypeError: camera.unpipe is not a function
    at ServerResponse.<anonymous> (/usr/lib/node_modules/mjpeg-camera/cs:50:14)
    at emitNone (events.js:67:13)
    at ServerResponse.emit (events.js:166:7)
    at Socket.onServerResponseClose (_http_server.js:131:44)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

```[root@cctv]# node -v
v4.1.1```

**Comment by mmaelzer** [comment]
Thanks for reporting that. I migrated from using streams2 back to streams1 as streams2 caused a considerable amount of headaches when trying to gracefully handle network reconnects to cameras. As a result of the streams2 => streams1 change, I broke the `cs` command. Commit 827daa3 fixes the issue.
